#source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'SwiftShopping' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'HandyJSON','5.0.2' #json处
  pod 'Moya', '~> 15.0.0'
  pod 'MJRefresh', '~> 3.7.5'
  pod 'SDWebImage', '~> 5.13.2'
end
#处理编译报错：The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99.
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
#        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#      end
#    end
#  end
#end
